In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b=np.zeros(5)
type(b)

numpy.ndarray

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a[1,5]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


13

In [ ]:
a[0,1:-5:1]

array([2])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[5,6,7]],dtype=float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 6. 7.]]


2

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,1]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11  1]]


In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.itemsize

8

In [ ]:
a=np.array([1,2,3])


In [ ]:
a.shape

(3,)

In [ ]:
a3=np.array([
   [ [1,2,3],[4,5,6]],
  [ [7,8,9],[10,11,12]]
])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a1=np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a1[0:3]=100
a1[3]=200
print(a1)

[100 100 100 200   4   5   6   7   8   9]


In [ ]:
slice=a1[5:9]
print(slice)
slice[:]=200
print(a1)

[5 6 7 8]
[100 100 100 200   4 200 200 200 200   9]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a*b
print(c)

[[ 5 12]
 [21 32]]


In [ ]:
w=np.array([[1,2],[3,4]])
print(w.T)

[[1 3]
 [2 4]]
